# --- Production Environment Configuration ---
# This file overrides dev.yaml for production runs.
# It points to live AWS services and production data paths.

vector_store_bucket: "placeholder-vector-store-bucket"
data_bucket: "placeholder-data-bucket"
log_level: "INFO"
api_timeout_seconds: 30
feature_flags: {}

data_source:
  type: "s3"
  bucket: "placeholder-data-bucket"
  prefix: "raw/"

embedding_service:
  type: "bedrock"
  aws_region: "af-south-1"
  model_id: "amazon.titan-embed-text-v1"

vector_repository:
  type: "faiss"
  persist_path: "/tmp/vector_store/faiss_index.bin"
  s3_bucket: "placeholder-vector-store-bucket"
  s3_key: "faiss_index.bin"
