# --- Staging Environment Configuration ---
# This file overrides dev for staging runs.
# It should mirror production as closely as possible, but point to staging resources.

vector_store_bucket: "placeholder-vector-store-bucket-staging"
data_bucket: "placeholder-data-bucket-staging"
log_level: "DEBUG"
api_timeout_seconds: 30
feature_flags: {}

data_source:
  type: "s3"
  bucket: "placeholder-data-bucket-staging"
  prefix: "raw/"

embedding_service:
  type: "bedrock"
  aws_region: "af-south-1"
  model_id: "amazon.titan-embed-text-v1"

vector_repository:
  type: "faiss"
  persist_path: "/tmp/vector_store/faiss_index.bin"
  s3_bucket: "placeholder-vector-store-bucket-staging"
  s3_key: "staging/faiss_index.bin"
