name: CodeCraft AI - CI/CD

on:
  # Trigger on pushes to the main branch for production deployments
  push:
    branches: [ "main" ]

  # Allow manual triggers for any branch, primarily for staging deployments
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - prod

env:
  AWS_REGION: af-south-1
  API_ECR_REPOSITORY: codecraft-ai-api
  INGESTION_ECR_REPOSITORY: codecraft-ai-ingestion
  # Set CDK_ENV based on the trigger event
  CDK_ENV: ${{ (github.event_name == 'push' && 'prod') || github.event.inputs.environment }}

permissions:
  contents: read
  id-token: write # passwordless auth to AWS

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: make install

      - name: Run linter
        shell: pwsh
        run: make lint

      - name: Run tests
        shell: pwsh
        run: make test

  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: lint-and-test
    # This job should run for pushes to main OR any manual workflow dispatch.
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsCdkDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and Push API Image
        shell: pwsh
        run: make build-and-push-api ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}

      - name: Build and Push Ingestion Image
        shell: pwsh
        run: make build-and-push-ingestion ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build-and-push
    # This job should run for pushes to main OR any manual workflow dispatch.
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsCdkDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK dependencies
        shell: pwsh
        run: make infra-install

      - name: Deploy CDK stack
        shell: pwsh
        run: make cdk-deploy CDK_ENV=${{ env.CDK_ENV }}

      - name: Force new ECS deployment
        id: ecs_deploy
        shell: pwsh
        run: |
          # Robustly find the stateless stack key in the JSON output
          $stackName = (Get-Content -Raw -Path cdk-outputs.json | ConvertFrom-Json | Get-Member -MemberType NoteProperty | Where-Object { $_.Name -like '*StatelessStack*' }).Name
          $cdkOutputs = Get-Content -Raw -Path cdk-outputs.json | ConvertFrom-Json
          $clusterName = $cdkOutputs.$stackName.EcsClusterName
          $serviceName = $cdkOutputs.$stackName.ApiServiceName
          $subnets = $cdkOutputs.$stackName.PrivateSubnetIds

          Write-Output "Forcing new deployment for service $serviceName in cluster $clusterName..."
          aws ecs update-service --cluster $clusterName --service $serviceName --force-new-deployment
