name: Security Scan

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC

jobs:
  pip-audit:
    name: PythonDependencyVulnerabilityScan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: pip install pip-audit

  trivy-scan:
    name: TrivyContainerVulnerabilityScan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-flags: --debug
          install: true

      - name: Ensure buildx cache directory exists
        run: mkdir -p /tmp/.buildx-cache

      - name: Build API image
        run: |
          docker buildx build --builder default --cache-from=type=local,src=/tmp/.buildx-cache \
                              --cache-to=type=local,dest=/tmp/.buildx-cache \
                              -f Dockerfile.api -t codecraft-ai-api:test .

      - name: Build Ingestion image
        run: |
          docker buildx build --builder default --cache-from=type=local,src=/tmp/.buildx-cache \
                              --cache-to=type=local,dest=/tmp/.buildx-cache \
                              -f Dockerfile.ingestion -t codecraft-ai-ingestion:test .

  gitleaks:
    name: GitleaksSecretsDetection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
