name: Validate AWS SSM Config

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  validate-config:
    name: Validate SSM Config Before Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: af-south-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 🟦 NOTE: Trivy and Python dependency scans are intentionally skipped for demo speed.
      # To re-enable, add the scan steps back here.

      - name: Validate SSM config for all environments
        run: |
          make validate-config CDK_ENV=dev
          make validate-config CDK_ENV=staging
          make validate-config CDK_ENV=prod
