# .github/workflows/validate-config.yml
name: Validate AWS SSM Config

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  validate-config:
    name: Validate SSM Config Before Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      # Optionally override in repo/environment secrets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements/dev.txt

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate SSM config for all environments
        run: |
          make validate-config CDK_ENV=dev
          make validate-config CDK_ENV=staging
          make validate-config CDK_ENV=prod
